Add ability to create scopes and collections
brantburnett/couchbasefakeit pull request #23
Opened 2020-12-18 17:37 UTC by jgroh9

# What was done

- Added a new script to create scopes and collections for Couchbase 7
- Updated the FakeIt script to insert fake data into a scope and/or collection based on the configuration a user provides.
    - I've chosen to use `cbimport` to handle this because it requires no changes to the FakeIt library to insert data to Couchbase. I started down the path of updating FakeIt but that opened up a can of worms that I do not have the time to spend to update since the last update was over 2 years ago.
- Added documentation to the readme on configuring scopes, collections, and how to insert fake data into a scope and/or collection
- Added sample configuration files for the scope/collection creation
- Tested new logic locally via modifying the Dockerfile and docker-compose file in the example/sample directory

**NOTE:** The one downside, as documented in the readme updates, is that you can only insert fake data into a single scope and you have to coordinate scope/collection configuration with FakeIt data generation

2020-12-21 13:42 UTC, brantburnett requested changes
First, let me say thanks so much for the submission. Scopes/collections are something we really need to get added, and I appreciate the assistance.

My one concern here is the way you're approaching fakeit. I agree that it's an effective approach for a single scope/collection, given the current limitations of fakeit. My worry is that, once we've added it working this way, we'll have to support this approach indefinitely for backward compatibility. It will be more than a little cumbersome once fakeit is up to snuff, especially since it forces the same scope/collection name for all buckets.

I'd like to propose that we pare this PR down a bit to just create the scopes/collections (for now), get that merged, and then work separately on how to make fakeit work better with scopes/collections.

2020-12-21 13:49 UTC, jgroh9 commented
Ok, I will make that change

2020-12-21 14:21 UTC, jgroh9 commented
Changes to remove FakeIt scope/collection data logic have been removed

2020-12-21 23:23 UTC, brantburnett requested changes
Just a few more details, looks great!

2020-12-21 23:23 UTC, brantburnett commented on scripts/create-collections.sh
> +      curl -Ss -X POST -u "$CB_USERNAME:$CB_PASSWORD" http://localhost:8091/pools/default/buckets/$bucketName/collections -d name=$scopeName
This ensures a newline in the script output

```suggestion
      curl -Ss -X POST -u "$CB_USERNAME:$CB_PASSWORD" http://localhost:8091/pools/default/buckets/$bucketName/collections -d name=$scopeName && echo
```

2020-12-21 23:23 UTC, brantburnett commented on scripts/create-collections.sh
> +      sleep 5
The sleep seems unnecessary in my testing

2020-12-21 23:23 UTC, brantburnett commented on scripts/create-collections.sh
> +      curl -Ss -X POST -u "$CB_USERNAME:$CB_PASSWORD" http://localhost:8091/pools/default/buckets/$bucketName/collections/$scopeName -d name=$collectionName
This ensures a newline in the script output

```suggestion
      curl -Ss -X POST -u "$CB_USERNAME:$CB_PASSWORD" http://localhost:8091/pools/default/buckets/$bucketName/collections/$scopeName -d name=$collectionName && echo
```

2020-12-22 01:02 UTC, jgroh9 commented
Requested changes made

2020-12-22 01:16 UTC, brantburnett approved these changes

2020-12-22 01:17 UTC, merged